[package]
name = "day02"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divan = "0.1.21"
fancy-regex = "0.16.2"


[[bench]]
name = "day02-bench"
path = "benches/benchmarks.rs"
harness = false
